apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tycho.fullname" . }}
  labels:
    {{- include "tycho.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      {{- include "tycho.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "tycho.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tycho.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tycho.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - bash
            - -c
            - >
              export INDEX=$((${HOSTNAME##*-}));
              export KEY="$(</keys/$INDEX)";
              /app/tycho debug mempool
              --key $KEY
              --config "/app/config.json"
              --global-config "/app/global-config.json"
              --import-zerostate "/app/zerostate.boc"
              --logger-config "/app/logger.json"
              --payload-step 50
              --steps-until-full 8
          env:
            - name: RUST_LOG
              value: {{ .Values.sharedConfigs.rustLog | quote }}
            - name: TYCHO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          {{- if .Values.serviceMonitor.enabled }}
            - name: metrics
              containerPort: {{ .Values.serviceMonitor.port }}
              protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.persistence }}
  {{- if not .Values.persistence.isLocal }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "tycho.labels" . | nindent 10 }}
      {{- with .Values.persistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        storageClassName: {{ .Values.persistence.storageClass }}
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}{{ .Values.persistence.sizeType }}
  {{- end }}
{{- end }}